In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("hugomathien/soccer")

print("Path to dataset files:", path)

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).
Path to dataset files: C:\Users\tijnd\.cache\kagglehub\datasets\hugomathien\soccer\versions\10

In [3]:
import sqlite3
import pandas as pd
import os

# Create the full path to the sqlite file
db_path = os.path.join(path, "database.sqlite")

# Connect to the database
conn = sqlite3.connect(db_path)

# Check what tables are inside
tables = pd.read_sql("SELECT name FROM sqlite_master WHERE type='table';", conn)
print(tables)

                name
0    sqlite_sequence
1  Player_Attributes
2             Player
3              Match
4             League
5            Country
6               Team
7    Team_Attributes

In [4]:
print("DataFrames:")
for table_name in tables['name']:
    query = f"SELECT * FROM {table_name}"
    lower_var_name = table_name.lower()
    print(f" - {lower_var_name}")
    # This creates a variable in your environment named after the table
    globals()[lower_var_name] = pd.read_sql(query, conn)

DataFrames:
 - sqlite_sequence
 - player_attributes
 - player
 - match
 - league
 - country
 - team
 - team_attributes

In [5]:
sqlite_sequence
# Er zijn in totaal 7 rijen en 2 kolommen
# Deze tabel registreert de tabel-IDs van de tabellen in de database. 
        # name = naam van de tabel (string)
        # seq = aantal rijen (int)
# Het vertelt niet hoeveel rijen er in de tabel zitten, maar de hoogst uitgegeven ID-waarde in die tabel.

                name     seq
0               Team  103916
1            Country   51958
2             League   51958
3              Match   51958
4             Player   11075
5  Player_Attributes  183978
6    Team_Attributes    1458

In [6]:
pd.set_option('display.max_columns', None)
import pandas as pd

def check_kolom(df, kolom_naam):
    """Functie om informatie te krijgen over een kolom, om hem te kunnen beschrijven"""
    print(kolom_naam)
    print(f"Datatype: {df[kolom_naam].dtype}")
    print(f"Missende waardes: {df[kolom_naam].isnull().sum()}")

    if pd.api.types.is_numeric_dtype(df[kolom_naam]):
        print(f"Maximale waarde: {df[kolom_naam].max()}")
        print(f"Minimale waarde: {df[kolom_naam].min()}")
    else:
        print("Maximale waarde: N.v.t. (tekstkolom)")
        print("Minimale waarde: N.v.t. (tekstkolom)")

    print("\nWaarde tellingen:")
    print(df[kolom_naam].value_counts().head(10))

check_kolom(player_attributes, 'gk_reflexes')

display(player_attributes.head(5))
# display(player_attributes.info())
# Er zijn in totaal 183978 rijen en 42 kolommen, er missen in 30 kolommen 836 waardes. Er zijn ook nog 7 kolommen waarbij 2713 waardes missen. 
# De kolom attacking_work_rate heeft de meeste missende waardes, namenlijk: 3230.
        # id = de ID van de speler in de tabel (int: 1-183978)
        # player_fifa_api_id = de ID van de speler in FIFA (int: 2-234141)
        # player_api_id = de ID van de speler in the Open Player Database (int: 2625-750584)
        # date = de datum waarop de attributen van de speler zijn opgehaald (object: 2007/02/22-2016/07/07)
        # overall_rating = de gemiddelde rating van de speler (float: 33-94)
        # potential = de maximaal haalbare rating van de speler in de toekomst (float: 39-97)
        # preferred_foot = de voorkeur voet van de speler (object: left, right)
        # attacking_work_rate = hoe hard de speler aanvalt (object: low, medium, high, None, norm, y, le, stoc)
        # defensive_work_rate = hoe hard de speler verdedigt (object: low, medium, high, _0, o, 1, ormal, 2, 3, 5, 7, 6, 0, 9, 4, es, ean, tocky, 8)
        # crossing = de score voor de voorzetten van de speler (float: 1-95)
        # finishing = de score voor de nauwkeurigheid van schoten op doel van de speler(float: 1-97)
        # heading_accuracy = de score voor de nauwkeurigheid van het koppen van de speler (float: 1-98)
        # short_passing = de score voor de nauwkeurigheid van de korte passen van de speler (float: 3-97)
        # volleys = de score voor het vermogen van de speler om een bal vanuit de lucht direct te schieten (float: 1-93)
        # dribbling = de score voor de nauwkeurigheid van de dribbling van de speler (float: 1-97)
        # curve = de score voor het vermogen om de bal met een boog/effect te trappen (float: 2-94)
        # free_kick_accuracy = de score voor de nauwkeurigheid van de speler bij het nemen van directe vrije trappen (float: 1-97)
        # long_passing = de score voor de nauwkeurigheid van de lange passen van de speler (float: 3-97)
        # ball_control = de score voor het vermogen van de speler om de bal onder controle te houden (float: 5-97)
        # acceleration = de score voor hoe snel de speler zijn maximale snelheid bereikt (float: 10-97)
        # sprint_speed = de score voor de maximale loopsnelheid van de speler (float: 12-97)
        # agility = de score voor de wendbaarheid van de speler bij het draaien en veranderen van richting (float: 11-96)
        # reactions = de score voor hoe snel de speler reageert op situaties op het veld (float: 17-97)
        # balance = de score voor het vermogen van de speler om zijn evenwicht te bewaren (float: 12-96)
        # shot_power = de score voor de kracht van het schot van de speler (float: 2-97)
        # jumping = de score voor de sprongkracht van de speler (float: 14-96)
        # stamina = de score voor het uithoudingsvermogen van de speler (float: 10-96)
        # strength = de score voor de fysieke kracht van de speler (float: 10-96)
        # long_shots = de score voor de nauwkeurigheid van schoten vanaf buiten het strafschopgebied (float: 10-96)
        # aggression = de score voor de mate van aggresie bij de speler (float: 6-97)
        # interceptions = de score voor het vermogen om passes te lezen en te onderscheppen van de speler (float: 1-96)
        # positioning = de score voor het vermogen van de speler om zich op de juist positie te positioneren (float: 2-96)
        # vision = de score voor het spelinzicht en overzicht om vrije medespelers en ruimtes te zien van de speler (float: 1-97)
        # penalties = de score voor de nauwkeurigheid van het nemen van penalties van de speler (float: 2-96)
        # marking = de score voor het vermogen om een tegenstander af te dekken en te volgen (float: 1-96)
        # standing_tackle = de score voor de nauwkeurigheid van de staande tackles van de speler (float: 1-95)
        # sliding_tackle = de score voor de nauwkeurigheid van de slide tackles van de speler (float: 2-95)
        # gk_diving = de score voor het vermogen van de speler om naar de hoeken te duiken en schoten te stoppen (float: 1-94)
        # gk_handling = de score voor het vermogen van de speler om de bal klemvast te pakken en vast te houden (float: 1-93)
        # gk_kicking = de score voor de afstand en nauwkeurigheid van de uittrap en passes van de de speler (float: 1-97)
        # gk_positioning = de score voor het vermogen van de speler om de juiste positie in het doel te kiezen (float: 1-96)
        # gk_reflexes = de score voor de reactiesnelheid van de speler op schoten op doel (float: 1-96)
# Statistieken van spelers, overgenomen uit de FIFA-gameserie (EA Sports)
# Aangezien er heel veel kolommen dezelfde hoeveelheid rijen met missende waarde hebben, zouden we de rijen met de missende waardes kunnen verwijderen

gk_reflexes
Datatype: float64
Missende waardes: 836
Maximale waarde: 96.0
Minimale waarde: 1.0

Waarde tellingen:
gk_reflexes
8.0     14156
10.0    14026
14.0    13908
7.0     13886
9.0     13721
13.0    13277
12.0    13043
6.0     12706
11.0    12704
15.0    10594
Name: count, dtype: int64

,id,player_fifa_api_id,player_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,finishing,heading_accuracy,short_passing,volleys,dribbling,curve,free_kick_accuracy,long_passing,ball_control,acceleration,sprint_speed,agility,reactions,balance,shot_power,jumping,stamina,strength,long_shots,aggression,interceptions,positioning,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
0,1,218353,505942,2016-02-18 00:00:00,67.0,71.0,right,medium,medium,49.0,44.0,71.0,61.0,44.0,51.0,45.0,39.0,64.0,49.0,60.0,64.0,59.0,47.0,65.0,55.0,58.0,54.0,76.0,35.0,71.0,70.0,45.0,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
1,2,218353,505942,2015-11-19 00:00:00,67.0,71.0,right,medium,medium,49.0,44.0,71.0,61.0,44.0,51.0,45.0,39.0,64.0,49.0,60.0,64.0,59.0,47.0,65.0,55.0,58.0,54.0,76.0,35.0,71.0,70.0,45.0,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
2,3,218353,505942,2015-09-21 00:00:00,62.0,66.0,right,medium,medium,49.0,44.0,71.0,61.0,44.0,51.0,45.0,39.0,64.0,49.0,60.0,64.0,59.0,47.0,65.0,55.0,58.0,54.0,76.0,35.0,63.0,41.0,45.0,54.0,48.0,65.0,66.0,69.0,6.0,11.0,10.0,8.0,8.0
3,4,218353,505942,2015-03-20 00:00:00,61.0,65.0,right,medium,medium,48.0,43.0,70.0,60.0,43.0,50.0,44.0,38.0,63.0,48.0,60.0,64.0,59.0,46.0,65.0,54.0,58.0,54.0,76.0,34.0,62.0,40.0,44.0,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
4,5,218353,505942,2007-02-22 00:00:00,61.0,65.0,right,medium,medium,48.0,43.0,70.0,60.0,43.0,50.0,44.0,38.0,63.0,48.0,60.0,64.0,59.0,46.0,65.0,54.0,58.0,54.0,76.0,34.0,62.0,40.0,44.0,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0

In [7]:
pd.set_option('display.max_columns', None)
import pandas as pd

def check_kolom(df, kolom_naam):
    """Functie om informatie te krijgen over een kolom, om hem te kunnen beschrijven"""
    print(kolom_naam)
    print(f"Datatype: {df[kolom_naam].dtype}")
    print(f"Missende waardes: {df[kolom_naam].isnull().sum()}")

    if pd.api.types.is_numeric_dtype(df[kolom_naam]):
        print(f"Maximale waarde: {df[kolom_naam].max()}")
        print(f"Minimale waarde: {df[kolom_naam].min()}")
    else:
        print("Maximale waarde: N.v.t. (tekstkolom)")
        print("Minimale waarde: N.v.t. (tekstkolom)")

    print("\nWaarde tellingen:")
    print(df[kolom_naam].value_counts().head(10))

check_kolom(player, 'weight')

display(player.head(5))
player.info()

# Deze tabel bevat de persoonlijke basisgegevens van alle spelers in de database.
        # id = het unieke rij-nummer in deze tabel (int: 1-11075)
        # player_api_id = de ID van de speler in the Open Player Database (int: 2625-750584)
        # player_name = de naam van de speler (object)
        # player_fifa_api_id = de ID van de speler in FIFA (int: 2-234141)
        # birthday = de geboortedatum van de speler (object: 1967/01/23-1999/04/24)
        # height = de lengte van de speler in cm (float: 157.48-208.28)
        # weight = het gewicht van de speler in lbs (int: 117-243)

weight
Datatype: int64
Missende waardes: 0
Maximale waarde: 243
Minimale waarde: 117

Waarde tellingen:
weight
165    811
176    697
154    660
172    656
168    600
159    595
163    577
161    565
170    551
174    488
Name: count, dtype: int64

,id,player_api_id,player_name,player_fifa_api_id,birthday,height,weight
0,1,505942,Aaron Appindangoye,218353,1992-02-29 00:00:00,182.88,187
1,2,155782,Aaron Cresswell,189615,1989-12-15 00:00:00,170.18,146
2,3,162549,Aaron Doran,186170,1991-05-13 00:00:00,170.18,163
3,4,30572,Aaron Galindo,140161,1982-05-08 00:00:00,182.88,198
4,5,23780,Aaron Hughes,17725,1979-11-08 00:00:00,182.88,154

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11060 entries, 0 to 11059
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  11060 non-null  int64
 1   player_api_id       11060 non-null  int64
 2   player_name         11060 non-null  object
 3   player_fifa_api_id  11060 non-null  int64
 4   birthday            11060 non-null  object
 5   height              11060 non-null  float64
 6   weight              11060 non-null  int64
dtypes: float64(1), int64(4), object(2)
memory usage: 605.0+ KB

In [45]:
pd.set_option('display.max_columns', None)
import pandas as pd

def check_kolom(df, kolom_naam):
    """Functie om informatie te krijgen over een kolom, om hem te kunnen beschrijven"""
    print(kolom_naam)
    print(f"Datatype: {df[kolom_naam].dtype}")
    print(f"Missende waardes: {df[kolom_naam].isnull().sum()}")

    if pd.api.types.is_numeric_dtype(df[kolom_naam]):
        print(f"Maximale waarde: {df[kolom_naam].max()}")
        print(f"Minimale waarde: {df[kolom_naam].min()}")
    else:
        print("Maximale waarde: N.v.t. (tekstkolom)")
        print("Minimale waarde: N.v.t. (tekstkolom)")

    print("\nWaarde tellingen:")
    print(df[kolom_naam].value_counts().head(10))

check_kolom(match, 'away_team_goal')
pd.set_option('display.max_rows', None)

display(match.head(5))
match.info()

match['date'].max()
# Deze tabel bevat de matchgegevens van alle matches in de database. Denk aan team id's, match id's en datums
        # id = het unieke rij-nummer in deze tabel (int: 1-25979) 
        # country_id = de ID van de land waar de match gespeeld werd (int: 1-24558)
        # league_id = de ID van de competitie waar de match gespeeld werd (int: 1-24558)
        # season = het seizoen waar de match gespeeld werd (object: 2008/2009-2015/2016)
        # stage = de stage waar de match gespeeld werd (int: 1-38)
        # date = de datum waar de match gespeeld werd (object: 2008/07/18-2016/05/25)
        # match_api_id = de API-ID van de match (int: 483129-2216672)
        # home_team_api_id = de API-ID van de thuis team (int: 1601-274581)
        # away_team_api_id = de API-ID van de uit team (int: 1-24558)
        # home_team_goal = het aantal goals van de thuis team (int: 0-10)
        # away_team_goal = het aantal goals van de uit team (int: 0-9)
match.isna().sum()

away_team_goal
Datatype: int64
Missende waardes: 0
Maximale waarde: 9
Minimale waarde: 0

Waarde tellingen:
away_team_goal
1    8989
0    8687
2    5146
3    2145
4     718
5     215
6      63
7      10
8       5
9       1
Name: count, dtype: int64

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal,home_player_X1,home_player_X2,home_player_X3,home_player_X4,home_player_X5,home_player_X6,home_player_X7,home_player_X8,home_player_X9,home_player_X10,home_player_X11,away_player_X1,away_player_X2,away_player_X3,away_player_X4,away_player_X5,away_player_X6,away_player_X7,away_player_X8,away_player_X9,away_player_X10,away_player_X11,home_player_Y1,home_player_Y2,home_player_Y3,home_player_Y4,home_player_Y5,home_player_Y6,home_player_Y7,home_player_Y8,home_player_Y9,home_player_Y10,home_player_Y11,away_player_Y1,away_player_Y2,away_player_Y3,away_player_Y4,away_player_Y5,away_player_Y6,away_player_Y7,away_player_Y8,away_player_Y9,away_player_Y10,away_player_Y11,home_player_1,home_player_2,home_player_3,home_player_4,home_player_5,home_player_6,home_player_7,home_player_8,home_player_9,home_player_10,home_player_11,away_player_1,away_player_2,away_player_3,away_player_4,away_player_5,away_player_6,away_player_7,away_player_8,away_player_9,away_player_10,away_player_11,goal,shoton,shotoff,foulcommit,card,cross,corner,possession,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,LBH,LBD,LBA,PSH,PSD,PSA,WHH,WHD,WHA,SJH,SJD,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA
0,1,1,1,2008/2009,1,2008-08-17 00:00:00,492473,9987,9993,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,1.73,3.40,5.00,1.75,3.35,4.20,1.85,3.2,3.5,1.80,3.3,3.75,NaN,NaN,NaN,1.70,3.30,4.33,1.90,3.3,4.00,1.65,3.40,4.50,1.78,3.25,4.00,1.73,3.40,4.20
1,2,1,1,2008/2009,1,2008-08-16 00:00:00,492474,10000,9994,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,1.95,3.20,3.60,1.80,3.30,3.95,1.90,3.2,3.5,1.90,3.2,3.50,NaN,NaN,NaN,1.83,3.30,3.60,1.95,3.3,3.80,2.00,3.25,3.25,1.85,3.25,3.75,1.91,3.25,3.60
2,3,1,1,2008/2009,1,2008-08-16 00:00:00,492475,9984,8635,0,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,2.38,3.30,2.75,2.40,3.30,2.55,2.60,3.1,2.3,2.50,3.2,2.50,NaN,NaN,NaN,2.50,3.25,2.40,2.63,3.3,2.50,2.35,3.25,2.65,2.50,3.20,2.50,2.30,3.20,2.75
3,4,1,1,2008/2009,1,2008-08-17 00:00:00,492476,9991,9998,5,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,1.44,3.75,7.50,1.40,4.00,6.80,1.40,3.9,6.0,1.44,3.6,6.50,NaN,NaN,NaN,1.44,3.75,6.00,1.44,4.0,7.50,1.45,3.75,6.50,1.50,3.75,5.50,1.44,3.75,6.50
4,5,1,1,2008/2009,1,2008-08-16 00:00:00,492477,7947,9985,1,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,5.00,3.50,1.65,5.00,3.50,1.60,4.00,3.3,1.7,4.00,3.4,1.72,NaN,NaN,NaN,4.20,3.40,1.70,4.50,3.5,1.73,4.50,3.40,1.65,4.50,3.50,1.65,4.75,3.30,1.67

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25979 entries, 0 to 25978
Columns: 115 entries, id to BSA
dtypes: float64(96), int64(9), object(10)
memory usage: 22.8+ MB

id                      0
country_id              0
league_id               0
season                  0
stage                   0
date                    0
match_api_id            0
home_team_api_id        0
away_team_api_id        0
home_team_goal          0
away_team_goal          0
home_player_X1       1821
home_player_X2       1821
home_player_X3       1832
home_player_X4       1832
home_player_X5       1832
home_player_X6       1832
home_player_X7       1832
home_player_X8       1832
home_player_X9       1832
home_player_X10      1832
home_player_X11      1832
away_player_X1       1832
away_player_X2       1832
away_player_X3       1832
away_player_X4       1832
away_player_X5       1832
away_player_X6       1832
away_player_X7       1832
away_player_X8       1832
away_player_X9       1833
away_player_X10      1833
away_player_X11      1839
home_player_Y1       1821
home_player_Y2       1821
home_player_Y3       1832
home_player_Y4       1832
home_player_Y5       1832
home_player_Y6       1832
home_player_Y7       1832
home_player_Y8       1832
home_player_Y9       1832
home_player_Y10      1832
home_player_Y11      1832
away_player_Y1       1832
away_player_Y2       1832
away_player_Y3       1832
away_player_Y4       1832
away_player_Y5       1832
away_player_Y6       1832
away_player_Y7       1832
away_player_Y8       1832
away_player_Y9       1833
away_player_Y10      1833
away_player_Y11      1839
home_player_1        1224
home_player_2        1315
home_player_3        1281
home_player_4        1323
home_player_5        1316
home_player_6        1325
home_player_7        1227
home_player_8        1309
home_player_9        1273
home_player_10       1436
home_player_11       1555
away_player_1        1234
away_player_2        1278
away_player_3        1293
away_player_4        1321
away_player_5        1335
away_player_6        1313
away_player_7        1235
away_player_8        1341
away_player_9        1328
away_player_10       1441
away_player_11       1554
goal                11762
shoton              11762
shotoff             11762
foulcommit          11762
card                11762
cross               11762
corner              11762
possession          11762
B365H                3387
B365D                3387
B365A                3387
BWH                  3404
BWD                  3404
BWA                  3404
IWH                  3459
IWD                  3459
IWA                  3459
LBH                  3423
LBD                  3423
LBA                  3423
PSH                 14811
PSD                 14811
PSA                 14811
WHH                  3408
WHD                  3408
WHA                  3408
SJH                  8882
SJD                  8882
SJA                  8882
VCH                  3411
VCD                  3411
VCA                  3411
GBH                 11817
GBD                 11817
GBA                 11817
BSH                 11818
BSD                 11818
BSA                 11818
dtype: int64

In [9]:
print("Row count for each DataFrame:")
for name in tables['name']:
    name = name.lower()
    df = globals()[name]
    print(name, ":", len(df))

Row count for each DataFrame:
sqlite_sequence : 7
player_attributes : 183978
player : 11060
match : 25979
league : 11
country : 11
team : 299
team_attributes : 1458

In [10]:
for table in tables['name']:
    table = table.lower()
    print(40 * "-")
    print("↓ Info for ", table, "↓")
    print(40 * "-")
    print(globals()[table].info())

----------------------------------------
↓ Info for  sqlite_sequence ↓
----------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    7 non-null      object
 1   seq     7 non-null      int64
dtypes: int64(1), object(1)
memory usage: 244.0+ bytes
None
----------------------------------------
↓ Info for  player_attributes ↓
----------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 183978 entries, 0 to 183977
Data columns (total 42 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   id                   183978 non-null  int64
 1   player_fifa_api_id   183978 non-null  int64
 2   player_api_id        183978 non-null  int64
 3   date                 183978 non-null  object
 4   overall_rating       183142 non-null  float64
 5   potential            183142 non-null  float64
 6   preferred_foot       183142 non-null  object
 7   attacking_work_rate  180748 non-null  object
 8   defensive_work_rate  183142 non-null  object
 9   crossing             183142 non-null  float64
 10  finishing            183142 non-null  float64
 11  heading_accuracy     183142 non-null  float64
 12  short_passing        183142 non-null  float64
 13  volleys              181265 non-null  float64
 14  dribbling            183142 non-null  float64
 15  curve                181265 non-null  float64
 16  free_kick_accuracy   183142 non-null  float64
 17  long_passing         183142 non-null  float64
 18  ball_control         183142 non-null  float64
 19  acceleration         183142 non-null  float64
 20  sprint_speed         183142 non-null  float64
 21  agility              181265 non-null  float64
 22  reactions            183142 non-null  float64
 23  balance              181265 non-null  float64
 24  shot_power           183142 non-null  float64
 25  jumping              181265 non-null  float64
 26  stamina              183142 non-null  float64
 27  strength             183142 non-null  float64
 28  long_shots           183142 non-null  float64
 29  aggression           183142 non-null  float64
 30  interceptions        183142 non-null  float64
 31  positioning          183142 non-null  float64
 32  vision               181265 non-null  float64
 33  penalties            183142 non-null  float64
 34  marking              183142 non-null  float64
 35  standing_tackle      183142 non-null  float64
 36  sliding_tackle       181265 non-null  float64
 37  gk_diving            183142 non-null  float64
 38  gk_handling          183142 non-null  float64
 39  gk_kicking           183142 non-null  float64
 40  gk_positioning       183142 non-null  float64
 41  gk_reflexes          183142 non-null  float64
dtypes: float64(35), int64(3), object(4)
memory usage: 59.0+ MB
None
----------------------------------------
↓ Info for  player ↓
----------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11060 entries, 0 to 11059
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  11060 non-null  int64
 1   player_api_id       11060 non-null  int64
 2   player_name         11060 non-null  object
 3   player_fifa_api_id  11060 non-null  int64
 4   birthday            11060 non-null  object
 5   height              11060 non-null  float64
 6   weight              11060 non-null  int64
dtypes: float64(1), int64(4), object(2)
memory usage: 605.0+ KB
None
----------------------------------------
↓ Info for  match ↓
----------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25979 entries, 0 to 25978
Columns: 115 entries, id to BSA
dtypes: float64(96), int64(9), object(10)
memory usage: 22.8+ MB
None
----------------------------------------
↓ Info for  league ↓
----------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          11 non-null     int64
 1   country_id  11 non-null     int64
 2   name        11 non-null     object
dtypes: int64(2), object(1)
memory usage: 396.0+ bytes
None
----------------------------------------
↓ Info for  country ↓
----------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      11 non-null     int64
 1   name    11 non-null     object
dtypes: int64(1), object(1)
memory usage: 308.0+ bytes
None
----------------------------------------
↓ Info for  team ↓
----------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                299 non-null    int64
 1   team_api_id       299 non-null    int64
 2   team_fifa_api_id  288 non-null    float64
 3   team_long_name    299 non-null    object
 4   team_short_name   299 non-null    object
dtypes: float64(1), int64(2), object(2)
memory usage: 11.8+ KB
None
----------------------------------------
↓ Info for  team_attributes ↓
----------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1458 entries, 0 to 1457
Data columns (total 25 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              1458 non-null   int64
 1   team_fifa_api_id                1458 non-null   int64
 2   team_api_id                     1458 non-null   int64
 3   date                            1458 non-null   object
 4   buildUpPlaySpeed                1458 non-null   int64
 5   buildUpPlaySpeedClass           1458 non-null   object
 6   buildUpPlayDribbling            489 non-null    float64
 7   buildUpPlayDribblingClass       1458 non-null   object
 8   buildUpPlayPassing              1458 non-null   int64
 9   buildUpPlayPassingClass         1458 non-null   object
 10  buildUpPlayPositioningClass     1458 non-null   object
 11  chanceCreationPassing           1458 non-null   int64
 12  chanceCreationPassingClass      1458 non-null   object
 13  chanceCreationCrossing          1458 non-null   int64
 14  chanceCreationCrossingClass     1458 non-null   object
 15  chanceCreationShooting          1458 non-null   int64
 16  chanceCreationShootingClass     1458 non-null   object
 17  chanceCreationPositioningClass  1458 non-null   object
 18  defencePressure                 1458 non-null   int64
 19  defencePressureClass            1458 non-null   object
 20  defenceAggression               1458 non-null   int64
 21  defenceAggressionClass          1458 non-null   object
 22  defenceTeamWidth                1458 non-null   int64
 23  defenceTeamWidthClass           1458 non-null   object
 24  defenceDefenderLineClass        1458 non-null   object
dtypes: float64(1), int64(11), object(13)
memory usage: 284.9+ KB
None

In [11]:
for table in tables['name']:
    table = table.lower()
    print(40 * "-")
    print("↓ Describe for ", table, "↓")
    print(40 * "-")
    display(globals()[table].describe())

----------------------------------------
↓ Describe for  sqlite_sequence ↓
----------------------------------------

                 seq
count       7.000000
mean    65185.857143
std     62082.942398
min      1458.000000
25%     31516.500000
50%     51958.000000
75%     77937.000000
max    183978.000000

----------------------------------------
↓ Describe for  player_attributes ↓
----------------------------------------

,id,player_fifa_api_id,player_api_id,overall_rating,potential,crossing,finishing,heading_accuracy,short_passing,volleys,dribbling,curve,free_kick_accuracy,long_passing,ball_control,acceleration,sprint_speed,agility,reactions,balance,shot_power,jumping,stamina,strength,long_shots,aggression,interceptions,positioning,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
count,183978.00000,183978.000000,183978.000000,183142.000000,183142.000000,183142.000000,183142.000000,183142.000000,183142.000000,181265.000000,183142.000000,181265.000000,183142.000000,183142.000000,183142.000000,183142.000000,183142.000000,181265.000000,183142.000000,181265.000000,183142.000000,181265.000000,183142.000000,183142.000000,183142.000000,183142.000000,183142.000000,183142.000000,181265.000000,183142.000000,183142.000000,183142.000000,181265.000000,183142.000000,183142.000000,183142.000000,183142.000000,183142.000000
mean,91989.50000,165671.524291,135900.617324,68.600015,73.460353,55.086883,49.921078,57.266023,62.429672,49.468436,59.175154,52.965675,49.380950,57.069880,63.388879,67.659357,68.051244,65.970910,66.103706,65.189496,61.808427,66.969045,67.038544,67.424529,53.339431,60.948046,52.009271,55.786504,57.873550,55.003986,46.772242,50.351257,48.001462,14.704393,16.063612,20.998362,16.132154,16.441439
std,53110.01825,53851.094769,136927.840510,7.041139,6.592271,17.242135,19.038705,16.488905,14.194068,18.256618,17.744688,18.255788,17.831746,14.394464,15.196671,12.983326,12.569721,12.954585,9.155408,13.063188,16.135143,11.006734,13.165262,12.072280,18.367025,16.089521,19.450133,18.448292,15.144086,15.546519,21.227667,21.483706,21.598778,16.865467,15.867382,21.452980,16.099175,17.198155
min,1.00000,2.000000,2625.000000,33.000000,39.000000,1.000000,1.000000,1.000000,3.000000,1.000000,1.000000,2.000000,1.000000,3.000000,5.000000,10.000000,12.000000,11.000000,17.000000,12.000000,2.000000,14.000000,10.000000,10.000000,1.000000,6.000000,1.000000,2.000000,1.000000,2.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,45995.25000,155798.000000,34763.000000,64.000000,69.000000,45.000000,34.000000,49.000000,57.000000,35.000000,52.000000,41.000000,36.000000,49.000000,58.000000,61.000000,62.000000,58.000000,61.000000,58.000000,54.000000,60.000000,61.000000,60.000000,41.000000,51.000000,34.000000,45.000000,49.000000,45.000000,25.000000,29.000000,25.000000,7.000000,8.000000,8.000000,8.000000,8.000000
50%,91989.50000,183488.000000,77741.000000,69.000000,74.000000,59.000000,53.000000,60.000000,65.000000,52.000000,64.000000,56.000000,50.000000,59.000000,67.000000,69.000000,69.000000,68.000000,67.000000,67.000000,65.000000,68.000000,69.000000,69.000000,58.000000,64.000000,57.000000,60.000000,60.000000,57.000000,50.000000,56.000000,53.000000,10.000000,11.000000,12.000000,11.000000,11.000000
75%,137983.75000,199848.000000,191080.000000,73.000000,78.000000,68.000000,65.000000,68.000000,72.000000,64.000000,72.000000,67.000000,63.000000,67.000000,73.000000,77.000000,77.000000,75.000000,72.000000,74.000000,73.000000,74.000000,76.000000,76.000000,67.000000,73.000000,68.000000,69.000000,69.000000,67.000000,66.000000,69.000000,67.000000,13.000000,15.000000,15.000000,15.000000,15.000000
max,183978.00000,234141.000000,750584.000000,94.000000,97.000000,95.000000,97.000000,98.000000,97.000000,93.000000,97.000000,94.000000,97.000000,97.000000,97.000000,97.000000,97.000000,96.000000,96.000000,96.000000,97.000000,96.000000,96.000000,96.000000,96.000000,97.000000,96.000000,96.000000,97.000000,96.000000,96.000000,95.000000,95.000000,94.000000,93.000000,97.000000,96.000000,96.000000

----------------------------------------
↓ Describe for  player ↓
----------------------------------------

,id,player_api_id,player_fifa_api_id,height,weight
count,11060.000000,11060.000000,11060.000000,11060.000000,11060.000000
mean,5537.511392,156582.427215,165664.910488,181.867445,168.380289
std,3197.692647,160713.700624,58649.928360,6.369201,14.990217
min,1.000000,2625.000000,2.000000,157.480000,117.000000
25%,2767.750000,35555.500000,151889.500000,177.800000,159.000000
50%,5536.500000,96619.500000,184671.000000,182.880000,168.000000
75%,8306.250000,212470.500000,203883.250000,185.420000,179.000000
max,11075.000000,750584.000000,234141.000000,208.280000,243.000000

----------------------------------------
↓ Describe for  match ↓
----------------------------------------

,id,country_id,league_id,stage,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal,home_player_X1,home_player_X2,home_player_X3,home_player_X4,home_player_X5,home_player_X6,home_player_X7,home_player_X8,home_player_X9,home_player_X10,home_player_X11,away_player_X1,away_player_X2,away_player_X3,away_player_X4,away_player_X5,away_player_X6,away_player_X7,away_player_X8,away_player_X9,away_player_X10,away_player_X11,home_player_Y1,home_player_Y2,home_player_Y3,home_player_Y4,home_player_Y5,home_player_Y6,home_player_Y7,home_player_Y8,home_player_Y9,home_player_Y10,home_player_Y11,away_player_Y1,away_player_Y2,away_player_Y3,away_player_Y4,away_player_Y5,away_player_Y6,away_player_Y7,away_player_Y8,away_player_Y9,away_player_Y10,away_player_Y11,home_player_1,home_player_2,home_player_3,home_player_4,home_player_5,home_player_6,home_player_7,home_player_8,home_player_9,home_player_10,home_player_11,away_player_1,away_player_2,away_player_3,away_player_4,away_player_5,away_player_6,away_player_7,away_player_8,away_player_9,away_player_10,away_player_11,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,LBH,LBD,LBA,PSH,PSD,PSA,WHH,WHD,WHA,SJH,SJD,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA
count,25979.000000,25979.000000,25979.000000,25979.000000,2.597900e+04,25979.000000,25979.000000,25979.000000,25979.000000,24158.000000,24158.000000,24147.000000,24147.000000,24147.000000,24147.000000,24147.000000,24147.000000,24147.000000,24147.000000,24147.000000,24147.000000,24147.000000,24147.000000,24147.000000,24147.00000,24147.000000,24147.000000,24147.000000,24146.000000,24146.000000,24140.000000,24158.000000,24158.000000,24147.000000,24147.000000,24147.000000,24147.000000,24147.000000,24147.000000,24147.000000,24147.000000,24147.00000,24147.000000,24147.0,24147.000000,24147.000000,24147.000000,24147.000000,24147.000000,24147.000000,24146.000000,24146.000000,24140.000000,24755.000000,24664.000000,24698.000000,24656.000000,24663.000000,24654.000000,24752.000000,24670.000000,24706.000000,24543.000000,24424.000000,24745.000000,24701.000000,24686.000000,24658.000000,24644.000000,24666.000000,24744.000000,24638.000000,24651.000000,24538.000000,24425.000000,22592.000000,22592.000000,22592.000000,22575.000000,22575.000000,22575.000000,22520.000000,22520.000000,22520.000000,22556.000000,22556.000000,22556.000000,11168.000000,11168.000000,11168.000000,22571.000000,22571.000000,22571.000000,17097.000000,17097.000000,17097.000000,22568.000000,22568.000000,22568.000000,14162.000000,14162.000000,14162.000000,14161.000000,14161.000000,14161.000000
mean,12990.000000,11738.630317,11738.630317,18.242773,1.195429e+06,9984.371993,9984.475115,1.544594,1.160938,0.999586,2.073516,4.061001,6.049199,7.544871,3.185158,4.769909,5.309604,5.822048,5.389407,5.783244,1.000290,2.074585,4.058558,6.052222,7.52549,3.195387,4.742660,5.294115,5.807546,5.476187,5.766114,0.999627,2.998634,3.000083,3.000414,3.237214,6.476954,6.672257,7.238953,8.026339,9.218868,10.43699,1.000248,3.0,3.000166,3.000248,3.245124,6.469706,6.680292,7.246366,8.022115,9.161186,10.455178,76638.362432,106854.091996,91601.289457,94540.204494,109527.842071,102308.768516,97287.636918,107290.992947,111131.536914,105612.508373,103413.870660,76628.199879,107614.617424,91126.781293,95083.910617,109800.936901,102308.262588,97898.056014,109265.114214,111087.003448,107149.115943,104932.876970,2.628818,3.839684,4.662222,2.559245,3.747597,4.396949,2.467613,3.608932,4.150575,2.536202,3.711740,4.385351,2.816447,4.132324,4.972744,2.578737,3.665295,4.482585,2.566061,3.755879,4.622343,2.668107,3.899048,4.840281,2.498764,3.648189,4.353097,2.497894,3.660742,4.405663
std,7499.635658,7553.936759,7553.936759,10.407354,4.946279e+05,14087.453758,14087.445135,1.297158,1.142110,0.022284,0.387185,0.385973,0.446024,1.609682,1.233609,1.092386,1.687376,1.968550,1.492068,0.759585,0.033438,0.403572,0.387047,0.448413,1.63765,1.284060,1.118226,1.687324,1.957116,1.541351,0.763611,0.024916,0.064003,0.012871,0.028777,0.940481,0.739988,0.588560,0.588947,1.126462,1.073893,0.50578,0.022292,0.0,0.025741,0.028779,0.955398,0.756391,0.586502,0.579881,1.126282,1.102167,0.498745,87556.226324,112619.266880,102703.003558,102789.967205,112787.542376,111514.726490,107050.579262,114527.022010,116221.869480,111528.262892,108761.188832,87428.953151,113758.447918,101438.583414,103845.905029,112450.715516,110861.276758,107359.030969,116358.092456,116492.957656,112397.540326,110237.525957,1.794463,1.118269,3.730104,1.637983,1.033468,3.292265,1.445642,0.803582,2.858912,1.640648,1.003846,3.398285,2.187924,1.516680,4.475458,1.685725,0.958069,3.585083,1.655535,0.999582,3.632164,1.928753,1.248221,4.318338,1.489299,0.867440,3.010189,1.507793,0.868272,3.189814
min,1.000000,1.000000,1.000000,1.000000,4.831290e+05,1601.000000,1601.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,3.000000,0.000000,0.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,1.000000,3.000000,1.00000,1.000000,3.0,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,5.000000,6.000000,7.000000,2984.000000,2802.000000,2752.000000,2752.000000,2752.000000,2625.000000,2625.000000,2625.000000,2625.000000,2625.000000,2802.000000,2796.000000,2790.000000,2752.000000,2752.000000,2790.000000,2625.000000,2625.000000,2625.000000,2625.000000,2770.000000,2802.000000,1.040000,1.400000,1.080000,1.030000,1.650000,1.100000,1.030000,1.500000,1.100000,1.040000,1.400000,1.100000,1.040000,2.200000,1.090000,1.020000,1.020000,1.080000,1.040000,1.400000,1.100000,1.030000,1.620000,1.080000,1.050000,1.450000,1.120000,1.040000,1.330000,1.120000
25%,6495.500000,4769.000000,4769.000000,9.000000,7.684365e+05,8475.000000,8475.000000,1.000000,0.000000,1.000000,2.000000,4.000000,6.000000,8.000000,2.000000,4.000000,3.000000,5.000000,4.000000,5.000000,1.000000,2.000000,4.000000,6.000000,8.00000,2.000000,4.000000,3.000000,5.000000,4.000000,5.000000,1.000000,3.000000,3.000000,3.000000,3.000000,6.000000,6.000000,7.000000,7.000000,8.000000,10.00000,1.000000,3.0,3.000000,3.000000,3.000000,6.000000,6.000000,7.000000,7.000000,8.000000,10.000000,30602.000000,32574.000000,30602.000000,30627.000000,33579.000000,31037.000000,30895.000000,32751.000000,33332.250000,32465.000000,32627.000000,30622.000000,32579.000000,30464.000000,30627.000000,33453.500000,31037.000000,30920.000000,32863.000000,33435.000000,32627.000000,32747.000000,1.670000,3.300000,2.500000,1.650000,3.200000,2.500000,1.650000,3.200000,2.500000,1.670000,3.200000,2.500000,1.720000,3.410000,2.560000,1.670000,3.200000,2.500000,1.670000,3.250000,2.500000,1.700000,3.300000,2.550000,1.670000,3.200000,2.500000,1.670000,3.250000,2.500000
50%,12990.000000,10257.000000,10257.000000,18.000000,1.147511e+06,8697.000000,8697.000000,1.000000,1.000000,1.000000,2.000000,4.000000,6.000000,8.000000,3.000000,5.000000,6.000000,5.000000,5.000000,6.000000,1.000000,2.000000,4.000000,6.000000,8.00000,3.000000,5.000000,6.000000,5.000000,5.000000,6.000000,1.000000,3.000000,3.000000,3.000000,3.000000,7.000000,7.000000,7.000000,8.000000,10.000000,10.00000,1.000000,3.0,3.000000,3.000000,3.000000,7.000000,7.000000,7.000000,8.000000,10.000000,10.000000,38230.000000,42388.000000,39731.000000,41060.000000,45996.000000,41467.000000,41432.000000,43319.000000,45605.000000,43296.000000,42091.000000,38289.000000,42388.000000,39892.000000,41083.000000,46212.000000,41634.500000,41433.000000,45816.000000,45860.000000,45358.000000,42652.000000,2.100000,3.500000,3.500000,2.100000,3.400000,3.400000,2.100000,3.300000,3.300000,2.100000,3.400000,3.300000,2.200000,3.640000,3.610000,2.150000,3.300000,3.400000,2.100000,3.400000,3.500000,2.150000,3.500000,3.500000,2.100000,3.300000,3.400000,2.100000,3.400000,3.400000
75%,19484.500000,17642.000000,17642.000000,27.000000,1.709852e+06,9925.000000,9925.000000,2.000000,2.000000,1.000000,2.000000,4.000000,6.000000,8.000000,4.000000,6.000000,7.000000,8.000000,7.000000,6.000000,1.000000,2.000000,4.000000,6.000000,8.00000,4.000000,6.000000,7.000000,8.000000,7.000000,6.000000,1.000000,3.000000,3.000000,3.000000,3.000000,7.000000,7.000000,8.000000,8.000000,10.000000,11.00000,1.000000,3.0,3.000000,3.000000,3.000000,7.000000,7.000000,8.000000,8.000000,10.000000,11.000000,96836.000000,159854.000000,128036.750000,145561.000000,160243.000000,150944.000000,141699.000000,160243.000000,164479.000000,158783.000000,161291.000000,96836.000000,159882.000000,121080.000000,145561.000000,160844.000000,151079.000000,144996.000000,163611.750000,164209.000000,161291.000000,161660.000000,2.800000,4.000000,5.250000,2.750000,3.800000,5.000000,2.600000,3.700000,4.600000,2.700000,3.750000,5.000000,2.980000,4.230000,5.410000,2.750000,3.750000,5.000000,2.750000,3.800000,5.250000,2.800000,4.000000,5.400000,2.650000,3.750000,5.000000,2.620000,3.750000,5.000000
max,25979.000000,24558.000000,24558.000000,38.000000,2.216672e+06,274581.000000,274581.000000,10.000000,9.000000,2.000000,8.000000,8.000000,8.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,7.000000,6.000000,8.000000,9.000000,8.000000,9.00000,9.000000,9.000000,9.000000,9.000000,9.000000,8.000000,3.000000,3.000000,5.000000,5.000000,8.000000,9.000000,9.000000,10.000000,10.000000,11.000000,11.00000,3.000000,3.0,7.000000,7.000000,9.000000,10.000000,10.000000,10.000000,11.000000,11.000000,11.000000,698273.000000,748432.000000,705484.000000,723037.000000,733787.000000,750584.000000,692984.000000,693171.000000,730065.000000,742405.000000,726956.000000,698273.000000,748432.000000,705484.000000,728414.000000,746419.000000,722766.000000,750435.000000,717248.000000,722766.000000,722766.000000,726956.000000,26.000000,17.000000,51.000000,34.000000,19.500000,51.000000,20.000000,11.000000,25.000000,26.000000,19.000000,51.000000,36.000000,29.000000,47.500000,26.000000,17.000000,51.000000,23.000000,15.000000,41.000000,36.000000,26.000000,67.000000,21.000000,11.000000,34.000000,17.000000,13.000000,34.000000

----------------------------------------
↓ Describe for  league ↓
----------------------------------------

                 id    country_id
count     11.000000     11.000000
mean   12452.090909  12452.090909
std     8215.308472   8215.308472
min        1.000000      1.000000
25%     6289.000000   6289.000000
50%    13274.000000  13274.000000
75%    18668.000000  18668.000000
max    24558.000000  24558.000000

----------------------------------------
↓ Describe for  country ↓
----------------------------------------

                 id
count     11.000000
mean   12452.090909
std     8215.308472
min        1.000000
25%     6289.000000
50%    13274.000000
75%    18668.000000
max    24558.000000

----------------------------------------
↓ Describe for  team ↓
----------------------------------------

                 id    team_api_id  team_fifa_api_id
count    299.000000     299.000000        288.000000
mean   23735.301003   12340.521739      21534.305556
std    15167.914719   25940.411135      42456.439408
min        1.000000    1601.000000          1.000000
25%     9552.500000    8349.000000        178.750000
50%    22805.000000    8655.000000        673.500000
75%    36250.500000    9886.500000       1910.750000
max    51606.000000  274581.000000     112513.000000

----------------------------------------
↓ Describe for  team_attributes ↓
----------------------------------------

,id,team_fifa_api_id,team_api_id,buildUpPlaySpeed,buildUpPlayDribbling,buildUpPlayPassing,chanceCreationPassing,chanceCreationCrossing,chanceCreationShooting,defencePressure,defenceAggression,defenceTeamWidth
count,1458.000000,1458.000000,1458.000000,1458.000000,489.000000,1458.000000,1458.000000,1458.000000,1458.000000,1458.000000,1458.000000,1458.000000
mean,729.500000,17706.982167,9995.727023,52.462277,48.607362,48.490398,52.165295,53.731824,53.969136,46.017147,49.251029,52.185871
std,421.032659,39179.857739,13264.869900,11.545869,9.678290,10.896101,10.360793,11.086796,10.327566,10.227225,9.738028,9.574712
min,1.000000,1.000000,1601.000000,20.000000,24.000000,20.000000,21.000000,20.000000,22.000000,23.000000,24.000000,29.000000
25%,365.250000,110.000000,8457.750000,45.000000,42.000000,40.000000,46.000000,47.000000,48.000000,39.000000,44.000000,47.000000
50%,729.500000,485.000000,8674.000000,52.000000,49.000000,50.000000,52.000000,53.000000,53.000000,45.000000,48.000000,52.000000
75%,1093.750000,1900.000000,9904.000000,62.000000,55.000000,55.000000,59.000000,62.000000,61.000000,51.000000,55.000000,58.000000
max,1458.000000,112513.000000,274581.000000,80.000000,77.000000,80.000000,80.000000,80.000000,80.000000,72.000000,72.000000,73.000000

In [12]:
# Zoek FC Barcelona in de team tabel
barca = team[team['team_long_name'] == 'FC Barcelona']
print(barca[['team_api_id', 'team_fifa_api_id', 'team_long_name', 'team_short_name']])

     team_api_id  team_fifa_api_id team_long_name team_short_name
258         8634             241.0   FC Barcelona             BAR